# Based on https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

name: Build and push images to registries

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

  # manually triggering the build
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse Repo Name
        id: repo-name
        run: |
          echo "::set-output name=repo::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=repo-clean::${GITHUB_REPOSITORY#*/docker-}"
          echo "::set-output name=org::${GITHUB_REPOSITORY%/*}"
          printf "::group::Outputs:\nrepo: ${GITHUB_REPOSITORY#*/}\nrepo-clean: ${GITHUB_REPOSITORY#*/docker-}\norg: ${GITHUB_REPOSITORY%/*}\n::endgroup::"

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.repo-clean }}
            ghcr.io/${{ steps.repo-name.outputs.org }}/${{ steps.repo-name.outputs.repo-clean }}
          tags: |
            type=sha,prefix=
            type=edge,branch=main
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
          flavor:

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
