# Based on https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

name: Build and push images to registries

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

  # manually triggering the build
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    env:
      DEFAULT_OS: ubuntu
    strategy:
      matrix:
        os: [ubuntu, alpine]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse Repo Name
        id: repo-name
        run: |
          echo "::set-output name=repo::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=repo_clean::${GITHUB_REPOSITORY#*/docker-}"
          echo "::set-output name=org::${GITHUB_REPOSITORY%/*}"
          printf "::group::Outputs:\nrepo: ${GITHUB_REPOSITORY#*/}\nrepo_clean: ${GITHUB_REPOSITORY#*/docker-}\norg: ${GITHUB_REPOSITORY%/*}\n::endgroup::"

      - name: configure metadata for building
        id: meta
        run: |
            # if this is the default OS
            if [ ${{ matrix.os }} == $DEFAULT_OS ]; then
              echo "::set-output name=is_default_os::true"
            else
              echo "::set-output name=is_default_os::false"
            fi

      - name: Docker metadata (OS tagged)
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.repo_clean }}
            ghcr.io/${{ steps.repo-name.outputs.org }}/${{ steps.repo-name.outputs.repo_clean }}
          flavor: |
            suffix=-${{ matrix.os }},onlatest=true
          tags: |
            type=sha,prefix=
            type=edge,branch=main
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr

      - name: Docker metadata (Default OS)
        id: docker_meta_default
        if: matrix.os == env.DEFAULT_OS
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.repo_clean }}
            ghcr.io/${{ steps.repo-name.outputs.org }}/${{ steps.repo-name.outputs.repo_clean }}
          tags: |
            type=sha,prefix=
            type=edge,branch=main
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.${{ matrix.os }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/riscv64,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ steps.docker_meta_default.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
